### ISSUE TITLE
Is there an Example App

### ISSUE THREAD

**Issue by dgleba** [JaneJeon/express-objection-starter#313]
Thanks for your efforts. It looks great.

Is there an example app using this I can look at?

Say a blog, or contact list, or something with roles and query-filter, etc.

**Comment by JaneJeon** [comment]
@dgleba this is "just" a template to get started with that provides authorization, authentication, basic user routes, sessions, ORM (objection) & (fast) logging setup, simple & isometric ACL that integrates into the ORM and can be used by both the frontend and the backend, a mechanism to prevent users from signin up with spam email addresses, an extremely easy and optimized email templating system (MJML) for all devices, a redis-backed queue (and a queued email sender that rate limits emails sent to ensure that your emails are delivered even when a process fails or you're using an external service), etc. backed with unit & integration tests.

So I do believe that all of this non-trivial setup is more than enough to be the base for building a production-ready app, and if you do use this as your starter, please let me know!

**Comment by dgleba** [comment]
I like what you are doing. I would really like your input on an example app. For example, there are probably many different ways to create a controller with a list/index, create, edit, delete actions and a query/filter/search box.

Is there any chance you could create a small contacts list to show how you would use your system?

Fields could be name, city, phone, birth_date, number_of_devices, created_at and updated_at.

**Comment by JaneJeon** [comment]
Thanks for the reply. Rather than separate out the controller with the routes, I integrate all route-related logic into, well, the routes. Because so much of the logic is already handled by the template's use of https://github.com/JaneJeon/objection-authorize, the views tend to be very anemic; hence my hesitation to create an _additional_ layer of unnecessary abstraction in form of a controller, not to mention that insulating logic inside the controller cause you to miss the often tightly-related route-specific middleware logic (e.g. you can't possibly tell inside a controller whether you authenticated the user or not, without duplicating the middleware logic into every single controller action).

For more examples, I implore you to take a look at what https://github.com/JaneJeon/lynx is doing, for example.
